### ISSUE TITLE
Clarification on ESP_GATT_AUTO_RSP/ESP_GATT_RSP_BY_APP

### ISSUE THREAD

**Issue by frazan-un** [eagi223/esp-idf_Bluetooth_Multi-Service#7] opened 2019-04-05 07:57 UTC
Hi,
Thank you for your code, I started from that to build my BLE section.
I'm confused about the different behavior of  ESP_GATT_AUTO_RSP/ESP_GATT_RSP_BY_APP.
If I use ESP_GATT_AUTO_RSP in read and write, the stack works for us and automatically send responses, but are the ESP_GATTS_[READ|WRITE|EXEC_WRITE]_EVT still triggered after?
If yes, in your code you however send responses and manage read and write with your functions, but aren't them a duplicate of what the stack already done? How do you recognize if an attribute is managed by the stack or not?
Thank you for your help!

**Comment by eagi223** [comment] 2019-04-05 17:12
When I originally wrote this for a project that I was working on, all I ever used was ESP_GATT_AUTO_RSP, so I never really checked to see if the manual functionality worked. I left it there because I started with the ESP-IDF BLE GATT Server example and built off of it. The example included the manual read/write/execute functions, so I left them. The relevant documentation for this is copied below from [here:](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gatt_defs.html#_CPPv416esp_gatt_value_t)

> _struct_ **esp_attr_control_t**
> attribute auto response flag
> 
> **Public Members**
> 
> uint8_t auto_rsp
> if auto_rsp set to ESP_GATT_RSP_BY_APP, means the response of Write/Read operation will by replied by application. if auto_rsp set to ESP_GATT_AUTO_RSP, means the response of Write/Read operation will be replied by GATT stack automatically.

At the moment, I've been doing a lot more C++ with the ESP-IDF, so I haven't come back to this and updated anything in awhile, but I do keep up with any issues and PRs. When I get a chance, I'm going to go through the repo and better document it.

**Comment by phatpaul** [comment] 2019-04-12 16:09
@frazan-un I had the same questions.  The bluedroid stack is rather confusing.  Please see my discussion with the Espressif guy: espressif/esp-idf#3102
I would like to write some documentation, but I don't have the time...

Now to specifically answer your questions:

- If I use ESP_GATT_AUTO_RSP in read and write, the stack works for us and automatically send responses, but are the ESP_GATTS_[READ|WRITE|EXEC_WRITE]_EVT still triggered after?

Yes, If ESP_GATT_AUTO_RSP, then ESP_GATTS_ (EXEC_) WRITE_EVT/ ESP_GATTS_READ_EVT triggers **After** a Write/Read.

- If yes, in your code you however send responses and manage read and write with your functions, but aren't them a duplicate of what the stack already done? 

In my example BLE-FTP code, the FTP_DATA_VAL characteristic makes use of ESP_GATT_RSP_BY_APP.  
This is because I need to change the characteristic value before it is sent.
Other attributes are AUTO because their value is static.

- How do you recognize if an attribute is managed by the stack or not?
I had this same question.  I originally thought to check it at runtime like this: 
```(devinfo_serv_gatt_db[attrIndex].attr_control.auto_rsp == ESP_GATT_RSP_BY_APP)```
But I think I later decided that it didn't matter - my code worked either way.

**Comment by frazan-un** [comment] 2019-04-16 09:23
Thank you! With your posts I solved al lot of doubts.

**Closed as completed** 2019-08-06 17:34 UTC
